from __future__ import annotations

import numpy as np
import pandas as pd



def run_backtest(
    features: pd.DataFrame,
    cfg: dict,
    strategy_name: str,
    accept_filter: pd.Series | None = None,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Run a one-unit, spread-neutral z-score strategy.

    Signals are based on the already-lagged `signal_zscore`. PnL at timestamp t is generated by
    the position held from t-1 over the contemporaneous change in the log spread. Costs are charged
    on every unit of position turnover, including closing trades.

    Args:
        features (pd.DataFrame): DataFrame containing strategy signals and market data.
            Must include `spread` and `signal_zscore` columns, indexed by timestamp.
        cfg (dict): Configuration dictionary containing backtest parameters under the
            "backtest" key (e.g., `entry_z`, `exit_z`, `stop_z`, `max_holding_days`,
            `transaction_cost_bps_per_leg`, `slippage_bps_per_leg`).
        strategy_name (str): Label identifier for the strategy being backtested.
        accept_filter (pd.Series | None, optional): Boolean series aligned with `features`
            index indicating whether new trade entries are allowed on a given date.
            Defaults to None (all entries allowed).

    Returns:
        tuple[pd.DataFrame, pd.DataFrame]: A tuple containing two DataFrames:
            - **frame** (pd.DataFrame): Original features augmented with backtest execution
              columns (`position`, `trade`, `gross_pnl`, `cost`, `net_pnl`, `exit_reason`,
              `cumulative_net_pnl`, and `drawdown`).
            - **trades** (pd.DataFrame): Detailed log of closed trades including entry/exit dates,
              z-scores, spreads, holding period, exit reasons, and trade net PnL.
    """
    bcfg = cfg["backtest"]
    entry_z = float(bcfg["entry_z"])
    exit_z = float(bcfg["exit_z"])
    stop_z = float(bcfg["stop_z"])
    max_holding = int(bcfg["max_holding_days"])
    per_asset_leg_cost = (
        float(bcfg.get("transaction_cost_bps_per_leg", 0.0))
        + float(bcfg.get("slippage_bps_per_leg", 0.0))
    ) / 10000.0
    # One unit of spread turnover trades both assets, so each position change has two legs.
    per_unit_cost = 2.0 * per_asset_leg_cost

    frame = features.copy().sort_index()
    frame["position"] = 0.0
    frame["trade"] = 0.0
    frame["gross_pnl"] = 0.0
    frame["cost"] = 0.0
    frame["net_pnl"] = 0.0
    frame["exit_reason"] = ""

    accept = None if accept_filter is None else accept_filter.reindex(frame.index).fillna(0).astype(bool)
    position = 0.0
    holding = 0
    entry_date = None
    entry_spread = None
    entry_zscore = None
    trades: list[dict] = []

    for i in range(1, len(frame)):
        spread_change = float(frame["spread"].iloc[i] - frame["spread"].iloc[i - 1])
        gross_pnl = position * spread_change
        signal_z = float(frame["signal_zscore"].iloc[i])
        new_position = position
        exit_reason = ""
        allow_entry = True if accept is None else bool(accept.iloc[i])

        if position == 0.0:
            holding = 0
            if allow_entry and abs(signal_z) >= entry_z:
                new_position = -float(np.sign(signal_z))
                entry_date = frame.index[i]
                entry_spread = float(frame["spread"].iloc[i])
                entry_zscore = signal_z
        else:
            holding += 1
            if abs(signal_z) <= exit_z:
                new_position = 0.0
                exit_reason = "convergence"
            elif abs(signal_z) >= stop_z:
                new_position = 0.0
                exit_reason = "stop_loss"
            elif holding >= max_holding:
                new_position = 0.0
                exit_reason = "max_holding"

        turnover = abs(new_position - position)
        cost = turnover * per_unit_cost
        frame.iloc[i, frame.columns.get_loc("position")] = new_position
        frame.iloc[i, frame.columns.get_loc("trade")] = new_position - position
        frame.iloc[i, frame.columns.get_loc("gross_pnl")] = gross_pnl
        frame.iloc[i, frame.columns.get_loc("cost")] = cost
        frame.iloc[i, frame.columns.get_loc("net_pnl")] = gross_pnl - cost
        frame.iloc[i, frame.columns.get_loc("exit_reason")] = exit_reason

        if position != 0.0 and new_position == 0.0 and entry_date is not None and entry_spread is not None:
            trade_slice = frame.loc[entry_date:frame.index[i], "net_pnl"]
            trades.append(
                {
                    "strategy": strategy_name,
                    "entry_date": entry_date,
                    "exit_date": frame.index[i],
                    "direction": position,
                    "entry_zscore": entry_zscore,
                    "entry_spread": entry_spread,
                    "exit_spread": float(frame["spread"].iloc[i]),
                    "holding_days": holding,
                    "exit_reason": exit_reason,
                    "net_pnl": float(trade_slice.sum()),
                }
            )
            entry_date = entry_spread = entry_zscore = None
            holding = 0
        position = new_position

    if position != 0.0 and len(frame) > 0:
        i = len(frame) - 1
        close_cost = abs(position) * per_unit_cost
        frame.iloc[i, frame.columns.get_loc("trade")] -= position
        frame.iloc[i, frame.columns.get_loc("cost")] += close_cost
        frame.iloc[i, frame.columns.get_loc("net_pnl")] -= close_cost
        frame.iloc[i, frame.columns.get_loc("position")] = 0.0
        frame.iloc[i, frame.columns.get_loc("exit_reason")] = "end_of_sample"
        if entry_date is not None and entry_spread is not None:
            trade_slice = frame.loc[entry_date:frame.index[i], "net_pnl"]
            trades.append(
                {
                    "strategy": strategy_name,
                    "entry_date": entry_date,
                    "exit_date": frame.index[i],
                    "direction": position,
                    "entry_zscore": entry_zscore,
                    "entry_spread": entry_spread,
                    "exit_spread": float(frame["spread"].iloc[i]),
                    "holding_days": holding,
                    "exit_reason": "end_of_sample",
                    "net_pnl": float(trade_slice.sum()),
                }
            )

    frame["cumulative_net_pnl"] = frame["net_pnl"].cumsum()
    frame["drawdown"] = frame["cumulative_net_pnl"] - frame["cumulative_net_pnl"].cummax()
    return frame, pd.DataFrame(trades)


def _sharpe(pnl: np.ndarray, cfg: dict) -> float:
    """Calculates the annualized Sharpe ratio for a series of PnL returns.

    Adjusts periodic daily returns by the annual risk-free rate and scales the
    mean-to-standard-deviation ratio by the square root of the annualization factor.

    Args:
        pnl (np.ndarray): Array of periodic (daily) net PnL values or returns.
        cfg (dict): Configuration dictionary containing backtest parameters under the
            "backtest" key (`annualization_factor`, `annual_risk_free_rate`).

    Returns:
        float: The computed annualized Sharpe ratio. Returns 0.0 if the standard
            deviation of excess returns is negligible (<= 1e-12).
    """
    bcfg = cfg["backtest"]
    annualization = float(bcfg.get("annualization_factor", 252))
    annual_rf = float(bcfg.get("annual_risk_free_rate", 0.0))
    daily_excess = pnl - annual_rf / annualization
    std = np.std(daily_excess, ddof=0)
    return float(np.sqrt(annualization) * np.mean(daily_excess) / std) if std > 1e-12 else 0.0


def _block_bootstrap_ci(pnl: pd.Series, cfg: dict, seed: int) -> dict[str, float]:
    """Computes block bootstrap confidence intervals for PnL and Sharpe ratio.

    Resamples contiguous blocks of PnL values to preserve time-series autocorrelation
    and constructs 95% confidence intervals (2.5th to 97.5th percentiles) for cumulative PnL
    and the Sharpe ratio.

    Args:
        pnl (pd.Series): Time series of daily net PnL values.
        cfg (dict): Configuration dictionary containing backtest parameters under the
            "backtest" key (`bootstrap_samples`, `bootstrap_block_length`).
        seed (int): Random seed for reproducible bootstrap sampling.

    Returns:
        dict[str, float]: A dictionary containing confidence interval boundaries:
            - `cumulative_pnl_ci_low` (float): Lower bound (2.5th percentile) of cumulative PnL.
            - `cumulative_pnl_ci_high` (float): Upper bound (97.5th percentile) of cumulative PnL.
            - `sharpe_ci_low` (float): Lower bound (2.5th percentile) of Sharpe ratio.
            - `sharpe_ci_high` (float): Upper bound (97.5th percentile) of Sharpe ratio.
            Returns `np.nan` for all values if sample size is insufficient or samples <= 0.
    """
    bcfg = cfg["backtest"]
    samples = int(bcfg.get("bootstrap_samples", 250))
    block = max(1, int(bcfg.get("bootstrap_block_length", 10)))
    values = pnl.to_numpy(dtype=float)
    if len(values) < block * 3 or samples <= 0:
        return {
            "cumulative_pnl_ci_low": np.nan,
            "cumulative_pnl_ci_high": np.nan,
            "sharpe_ci_low": np.nan,
            "sharpe_ci_high": np.nan,
        }
    rng = np.random.default_rng(seed)
    cumulative: list[float] = []
    sharpes: list[float] = []
    starts = np.arange(0, len(values) - block + 1)
    n_blocks = int(np.ceil(len(values) / block))
    for _ in range(samples):
        sampled = np.concatenate([values[start:start + block] for start in rng.choice(starts, n_blocks, replace=True)])[: len(values)]
        cumulative.append(float(sampled.sum()))
        sharpes.append(_sharpe(sampled, cfg))
    return {
        "cumulative_pnl_ci_low": float(np.quantile(cumulative, 0.025)),
        "cumulative_pnl_ci_high": float(np.quantile(cumulative, 0.975)),
        "sharpe_ci_low": float(np.quantile(sharpes, 0.025)),
        "sharpe_ci_high": float(np.quantile(sharpes, 0.975)),
    }


def summarize_backtest(results: pd.DataFrame, trades: pd.DataFrame, name: str, cfg: dict, seed: int = 42, compute_ci: bool = True) -> dict:
    """Generates a summary dictionary of key performance indicators for a backtest run.

    Aggregates overall performance metrics such as cumulative net PnL, Sharpe ratio,
    maximum drawdown, trade win rates, profit factor, turnover, and total costs.
    Optionally includes block bootstrap confidence intervals.

    Args:
        results (pd.DataFrame): Backtest output DataFrame containing time-series metrics
            including `net_pnl`, `cumulative_net_pnl`, `drawdown`, `trade`, and `cost`.
        trades (pd.DataFrame): Backtest output DataFrame containing individual closed trade logs.
        name (str): Name of the strategy being summarized.
        cfg (dict): Configuration dictionary containing backtest and risk-free rate parameters.
        seed (int, optional): Random seed for bootstrap confidence interval calculation.
            Defaults to 42.
        compute_ci (bool, optional): Whether to compute block-bootstrap confidence intervals.
            Defaults to True.

    Returns:
        dict: Summary statistics dictionary containing strategy performance metrics
            (e.g., `cumulative_net_pnl`, `sharpe`, `max_drawdown`, `profit_factor`,
            `trade_win_rate`, `total_cost`, and bootstrap CI bounds if computed).
    """
    pnl = results["net_pnl"].fillna(0.0)
    cumulative = results["cumulative_net_pnl"]
    gross_profit = float(pnl[pnl > 0].sum())
    gross_loss = float(abs(pnl[pnl < 0].sum()))
    closed_trade_count = int(len(trades))
    trade_win_rate = float((trades["net_pnl"] > 0).mean()) if closed_trade_count else 0.0
    average_holding = float(trades["holding_days"].mean()) if closed_trade_count else 0.0
    summary = {
        "strategy": name,
        "start": str(results.index.min().date()) if hasattr(results.index.min(), "date") else str(results.index.min()),
        "end": str(results.index.max().date()) if hasattr(results.index.max(), "date") else str(results.index.max()),
        "cumulative_net_pnl": float(cumulative.iloc[-1]),
        "sharpe": _sharpe(pnl.to_numpy(), cfg),
        "max_drawdown": float(results["drawdown"].min()),
        "active_day_win_rate": float((pnl[pnl != 0] > 0).mean()) if (pnl != 0).any() else 0.0,
        "closed_trades": closed_trade_count,
        "trade_win_rate": trade_win_rate,
        "average_holding_days": average_holding,
        "turnover": float(results["trade"].abs().sum()),
        "total_cost": float(results["cost"].sum()),
        "profit_factor": float(gross_profit / gross_loss) if gross_loss > 1e-12 else np.nan,
        "annual_risk_free_rate": float(cfg["backtest"].get("annual_risk_free_rate", 0.0)),
    }
    if compute_ci:
        summary.update(_block_bootstrap_ci(pnl, cfg, seed))
    else:
        summary.update({
            "cumulative_pnl_ci_low": np.nan,
            "cumulative_pnl_ci_high": np.nan,
            "sharpe_ci_low": np.nan,
            "sharpe_ci_high": np.nan,
        })
    return summary
