from __future__ import annotations

from pathlib import Path
import pandas as pd


def ensure_output_dirs(tables_dir: str | Path, figures_dir: str | Path) -> tuple[Path, Path]:
    tables = Path(tables_dir)
    figures = Path(figures_dir)
    tables.mkdir(parents=True, exist_ok=True)
    figures.mkdir(parents=True, exist_ok=True)
    return tables, figures


def save_table(df: pd.DataFrame, path: str | Path) -> None:
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(path, index=False)


def write_initial_findings_markdown(path: str | Path, pairs: pd.DataFrame, model_metrics: pd.DataFrame, strategy_metrics: pd.DataFrame) -> None:
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    text = [
        "# Initial Findings and Temporary Results",
        "",
        "These results are generated by the current starter pipeline and should be treated as temporary until the full data universe, final parameters, and validation plan are finalized.",
        "",
        "## Candidate pairs",
        pairs.head(10).to_markdown(index=False) if not pairs.empty else "No candidate pairs were selected.",
        "",
        "## Model metrics",
        model_metrics.to_markdown(index=False) if not model_metrics.empty else "Model training was skipped due to insufficient labels.",
        "",
        "## Strategy metrics",
        strategy_metrics.to_markdown(index=False) if not strategy_metrics.empty else "No backtest metrics were generated.",
        "",
    ]
    Path(path).write_text("\n".join(text), encoding="utf-8")
